name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
    - run: ./gradlew assembleDebug
    - uses: actions/upload-artifact@v2
      with:
        name: apk
        path: app/build/outputs/apk/debug/app-debug.apk
